
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-15T13:18:07+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "c98789d2a28bd436f83c933e8ac8749488ad6491",
 "version": "1.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
