
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-17T13:20:53+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "9b59d9993637e7880bf57d2df2e24aced4b456a0",
 "version": "v0.13.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
