
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-16T10:24:03+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "657a1d1a88911412c70b627d47a40068842cba7b",
 "version": "1.2.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
