# -*- coding: utf-8 -*-
from setuptools import setup

packages = \
['getlooks', 'getlooks.tmp.test']

package_data = \
{'': ['*'],
 'getlooks': ['test/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/chrome/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/cinnamon/*',
              'themes/GTK3/4 '
              'Themes/ChromeOS-UltraViolet-Rounded/cinnamon/assets/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/gnome-shell/*',
              'themes/GTK3/4 '
              'Themes/ChromeOS-UltraViolet-Rounded/gnome-shell/assets/*',
              'themes/GTK3/4 '
              'Themes/ChromeOS-UltraViolet-Rounded/gnome-shell/assets/dash/*',
              'themes/GTK3/4 '
              'Themes/ChromeOS-UltraViolet-Rounded/gnome-shell/extensions/workspaces-to-dock/*',
              'themes/GTK3/4 '
              'Themes/ChromeOS-UltraViolet-Rounded/gnome-shell/icons/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/gtk-2.0/*',
              'themes/GTK3/4 '
              'Themes/ChromeOS-UltraViolet-Rounded/gtk-2.0/assets/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/gtk-3.0/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/gtk-assets/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/gtk-icons/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/metacity-1/*',
              'themes/GTK3/4 '
              'Themes/ChromeOS-UltraViolet-Rounded/metacity-1/assets/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/plank/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/unity/*',
              'themes/GTK3/4 Themes/ChromeOS-UltraViolet-Rounded/xfwm4/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/assets/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/cinnamon/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-Blue/cinnamon/common-assets/menu/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-Blue/cinnamon/common-assets/misc/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-Blue/cinnamon/common-assets/panel/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-Blue/cinnamon/common-assets/switch/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-Blue/cinnamon/dark-assets/checkbox/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-Blue/cinnamon/dark-assets/menu/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-Blue/cinnamon/dark-assets/misc/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-Blue/cinnamon/dark-assets/switch/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/gnome-shell/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/gnome-shell/assets/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/gtk-2.0/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/gtk-2.0/apps/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/gtk-2.0/assets/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/gtk-3.0/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/gtk-4.0/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/metacity-1/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-Blue/xfwm4/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/assets/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/cinnamon/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-v40/cinnamon/common-assets/menu/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-v40/cinnamon/common-assets/misc/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-v40/cinnamon/common-assets/panel/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-v40/cinnamon/common-assets/switch/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-v40/cinnamon/dark-assets/checkbox/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-v40/cinnamon/dark-assets/menu/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-v40/cinnamon/dark-assets/misc/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar-v40/cinnamon/dark-assets/switch/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/gnome-shell/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/gnome-shell/assets/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/gtk-2.0/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/gtk-2.0/apps/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/gtk-2.0/assets/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/gtk-3.0/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/gtk-4.0/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/metacity-1/*',
              'themes/GTK3/4 Themes/Sweet-Ambar-v40/xfwm4/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/assets/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/cinnamon/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/cinnamon/common-assets/menu/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/cinnamon/common-assets/misc/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/cinnamon/common-assets/panel/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar/cinnamon/common-assets/switch/*',
              'themes/GTK3/4 '
              'Themes/Sweet-Ambar/cinnamon/dark-assets/checkbox/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/cinnamon/dark-assets/menu/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/cinnamon/dark-assets/misc/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/cinnamon/dark-assets/switch/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/gnome-shell/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/gnome-shell/assets/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/gtk-2.0/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/gtk-2.0/apps/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/gtk-2.0/assets/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/gtk-3.0/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/gtk-4.0/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/metacity-1/*',
              'themes/GTK3/4 Themes/Sweet-Ambar/xfwm4/*',
              'themes/GTK3/4 Themes/Sweet-Dark/*',
              'themes/GTK3/4 Themes/Sweet-Dark/assets/*',
              'themes/GTK3/4 Themes/Sweet-Dark/cinnamon/*',
              'themes/GTK3/4 Themes/Sweet-Dark/cinnamon/common-assets/menu/*',
              'themes/GTK3/4 Themes/Sweet-Dark/cinnamon/common-assets/misc/*',
              'themes/GTK3/4 Themes/Sweet-Dark/cinnamon/common-assets/panel/*',
              'themes/GTK3/4 Themes/Sweet-Dark/cinnamon/common-assets/switch/*',
              'themes/GTK3/4 Themes/Sweet-Dark/cinnamon/dark-assets/checkbox/*',
              'themes/GTK3/4 Themes/Sweet-Dark/cinnamon/dark-assets/menu/*',
              'themes/GTK3/4 Themes/Sweet-Dark/cinnamon/dark-assets/misc/*',
              'themes/GTK3/4 Themes/Sweet-Dark/cinnamon/dark-assets/switch/*',
              'themes/GTK3/4 Themes/Sweet-Dark/gnome-shell/*',
              'themes/GTK3/4 Themes/Sweet-Dark/gnome-shell/assets/*',
              'themes/GTK3/4 Themes/Sweet-Dark/gtk-2.0/*',
              'themes/GTK3/4 Themes/Sweet-Dark/gtk-2.0/apps/*',
              'themes/GTK3/4 Themes/Sweet-Dark/gtk-2.0/assets/*',
              'themes/GTK3/4 Themes/Sweet-Dark/gtk-3.0/*',
              'themes/GTK3/4 Themes/Sweet-Dark/gtk-4.0/*',
              'themes/GTK3/4 Themes/Sweet-Dark/metacity-1/*',
              'themes/GTK3/4 Themes/Sweet-Dark/xfwm4/*',
              'themes/GTK3/4 Themes/Sweet-mars/*',
              'themes/GTK3/4 Themes/Sweet-mars/assets/*',
              'themes/GTK3/4 Themes/Sweet-mars/cinnamon/*',
              'themes/GTK3/4 Themes/Sweet-mars/cinnamon/common-assets/menu/*',
              'themes/GTK3/4 Themes/Sweet-mars/cinnamon/common-assets/misc/*',
              'themes/GTK3/4 Themes/Sweet-mars/cinnamon/common-assets/panel/*',
              'themes/GTK3/4 Themes/Sweet-mars/cinnamon/common-assets/switch/*',
              'themes/GTK3/4 Themes/Sweet-mars/cinnamon/dark-assets/checkbox/*',
              'themes/GTK3/4 Themes/Sweet-mars/cinnamon/dark-assets/menu/*',
              'themes/GTK3/4 Themes/Sweet-mars/cinnamon/dark-assets/misc/*',
              'themes/GTK3/4 Themes/Sweet-mars/cinnamon/dark-assets/switch/*',
              'themes/GTK3/4 Themes/Sweet-mars/gnome-shell/*',
              'themes/GTK3/4 Themes/Sweet-mars/gnome-shell/assets/*',
              'themes/GTK3/4 Themes/Sweet-mars/gtk-2.0/*',
              'themes/GTK3/4 Themes/Sweet-mars/gtk-2.0/apps/*',
              'themes/GTK3/4 Themes/Sweet-mars/gtk-2.0/assets/*',
              'themes/GTK3/4 Themes/Sweet-mars/gtk-3.0/*',
              'themes/GTK3/4 Themes/Sweet-mars/gtk-4.0/*',
              'themes/GTK3/4 Themes/Sweet-mars/metacity-1/*',
              'themes/GTK3/4 Themes/Sweet-mars/xfwm4/*',
              'themes/GTK3/4 Themes/Sweet-v40/*',
              'themes/GTK3/4 Themes/Sweet-v40/assets/*',
              'themes/GTK3/4 Themes/Sweet-v40/cinnamon/*',
              'themes/GTK3/4 Themes/Sweet-v40/cinnamon/common-assets/menu/*',
              'themes/GTK3/4 Themes/Sweet-v40/cinnamon/common-assets/misc/*',
              'themes/GTK3/4 Themes/Sweet-v40/cinnamon/common-assets/panel/*',
              'themes/GTK3/4 Themes/Sweet-v40/cinnamon/common-assets/switch/*',
              'themes/GTK3/4 Themes/Sweet-v40/cinnamon/dark-assets/checkbox/*',
              'themes/GTK3/4 Themes/Sweet-v40/cinnamon/dark-assets/menu/*',
              'themes/GTK3/4 Themes/Sweet-v40/cinnamon/dark-assets/misc/*',
              'themes/GTK3/4 Themes/Sweet-v40/cinnamon/dark-assets/switch/*',
              'themes/GTK3/4 Themes/Sweet-v40/gnome-shell/*',
              'themes/GTK3/4 Themes/Sweet-v40/gnome-shell/assets/*',
              'themes/GTK3/4 Themes/Sweet-v40/gtk-2.0/*',
              'themes/GTK3/4 Themes/Sweet-v40/gtk-2.0/apps/*',
              'themes/GTK3/4 Themes/Sweet-v40/gtk-2.0/assets/*',
              'themes/GTK3/4 Themes/Sweet-v40/gtk-3.0/*',
              'themes/GTK3/4 Themes/Sweet-v40/gtk-4.0/*',
              'themes/GTK3/4 Themes/Sweet-v40/metacity-1/*',
              'themes/GTK3/4 Themes/Sweet-v40/xfwm4/*',
              'themes/GTK3/4 Themes/Sweet/*',
              'themes/GTK3/4 Themes/Sweet/assets/*',
              'themes/GTK3/4 Themes/Sweet/cinnamon/*',
              'themes/GTK3/4 Themes/Sweet/cinnamon/common-assets/menu/*',
              'themes/GTK3/4 Themes/Sweet/cinnamon/common-assets/misc/*',
              'themes/GTK3/4 Themes/Sweet/cinnamon/common-assets/panel/*',
              'themes/GTK3/4 Themes/Sweet/cinnamon/common-assets/switch/*',
              'themes/GTK3/4 Themes/Sweet/cinnamon/dark-assets/checkbox/*',
              'themes/GTK3/4 Themes/Sweet/cinnamon/dark-assets/menu/*',
              'themes/GTK3/4 Themes/Sweet/cinnamon/dark-assets/misc/*',
              'themes/GTK3/4 Themes/Sweet/cinnamon/dark-assets/switch/*',
              'themes/GTK3/4 Themes/Sweet/gnome-shell/*',
              'themes/GTK3/4 Themes/Sweet/gnome-shell/assets/*',
              'themes/GTK3/4 Themes/Sweet/gtk-2.0/*',
              'themes/GTK3/4 Themes/Sweet/gtk-2.0/apps/*',
              'themes/GTK3/4 Themes/Sweet/gtk-2.0/assets/*',
              'themes/GTK3/4 Themes/Sweet/gtk-3.0/*',
              'themes/GTK3/4 Themes/Sweet/gtk-4.0/*',
              'themes/GTK3/4 Themes/Sweet/metacity-1/*',
              'themes/GTK3/4 Themes/Sweet/xfwm4/*',
              'themes/GTK3/4 Themes/WhiteSur-Dark-solid/*',
              'themes/GTK3/4 Themes/WhiteSur-Dark-solid/cinnamon/*',
              'themes/GTK3/4 Themes/WhiteSur-Dark-solid/cinnamon/assets/*',
              'themes/GTK3/4 Themes/WhiteSur-Dark-solid/gnome-shell/*',
              'themes/GTK3/4 Themes/WhiteSur-Dark-solid/gnome-shell/assets/*',
              'themes/GTK3/4 '
              'Themes/WhiteSur-Dark-solid/gnome-shell/icons/scalable/actions/*',
              'themes/GTK3/4 '
              'Themes/WhiteSur-Dark-solid/gnome-shell/icons/scalable/status/*',
              'themes/GTK3/4 Themes/WhiteSur-Dark-solid/gtk-2.0/*',
              'themes/GTK3/4 Themes/WhiteSur-Dark-solid/gtk-2.0/assets/*',
              'themes/GTK3/4 Themes/WhiteSur-Dark-solid/gtk-3.0/*',
              'themes/GTK3/4 Themes/WhiteSur-Dark-solid/gtk-4.0/*',
              'themes/GTK3/4 Themes/WhiteSur-Dark-solid/metacity-1/*',
              'themes/GTK3/4 '
              'Themes/WhiteSur-Dark-solid/metacity-1/titlebuttons/*',
              'themes/GTK3/4 Themes/WhiteSur-Dark-solid/plank/*',
              'themes/GTK3/4 Themes/WhiteSur-Light-solid/*',
              'themes/GTK3/4 Themes/WhiteSur-Light-solid/cinnamon/*',
              'themes/GTK3/4 Themes/WhiteSur-Light-solid/cinnamon/assets/*',
              'themes/GTK3/4 Themes/WhiteSur-Light-solid/gnome-shell/*',
              'themes/GTK3/4 Themes/WhiteSur-Light-solid/gnome-shell/assets/*',
              'themes/GTK3/4 '
              'Themes/WhiteSur-Light-solid/gnome-shell/icons/scalable/actions/*',
              'themes/GTK3/4 '
              'Themes/WhiteSur-Light-solid/gnome-shell/icons/scalable/status/*',
              'themes/GTK3/4 Themes/WhiteSur-Light-solid/gtk-2.0/*',
              'themes/GTK3/4 Themes/WhiteSur-Light-solid/gtk-2.0/assets/*',
              'themes/GTK3/4 Themes/WhiteSur-Light-solid/gtk-3.0/*',
              'themes/GTK3/4 Themes/WhiteSur-Light-solid/gtk-4.0/*',
              'themes/GTK3/4 Themes/WhiteSur-Light-solid/metacity-1/*',
              'themes/GTK3/4 '
              'Themes/WhiteSur-Light-solid/metacity-1/titlebuttons/*',
              'themes/GTK3/4 Themes/WhiteSur-Light-solid/plank/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/cinnamon/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/cinnamon/assets/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/gnome-shell/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/gnome-shell/assets/*',
              'themes/GTK3/4 '
              'Themes/WhiteSur-Light/gnome-shell/icons/scalable/actions/*',
              'themes/GTK3/4 '
              'Themes/WhiteSur-Light/gnome-shell/icons/scalable/status/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/gtk-2.0/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/gtk-2.0/assets/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/gtk-3.0/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/gtk-4.0/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/metacity-1/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/metacity-1/titlebuttons/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/plank/*',
              'themes/GTK3/4 Themes/WhiteSur-Light/xfwm4/*',
              'tmp/*']}

install_requires = \
['beautifulsoup4',
 'colorama',
 'lxml',
 'requests',
 'rich>=12.4.0',
 'typer>=0.4.1,<0.5.0']

entry_points = \
{'console_scripts': ['gnomelooks = getlooks.cli:app']}

setup_kwargs = {
    'name': 'gnomelooks',
    'version': '0.1.9',
    'description': '',
    'long_description': '# Gnome-looks themes cli downloader\n\n[![Installs](https://static.pepy.tech/personalized-badge/gnomelooks?period=total&units=international_system&left_color=black&right_color=orange&left_text=Downloads)](https://pepy.tech/project/gnomelooks) ![Release version](https://img.shields.io/github/v/release/Rishang/gnome-theme-installer.svg?style=flat-square\n)\n\n\n**A cli-tool to install and update gnome based Icons, GTK, Cursor themes easily**\n\n### Supported desktop environments\n\n- **Gnone**\n- **Xfce**\n- **KDE Plasma**\n\n![image 1](./.github/images/get.png)\n\n## gnomelooks cli usage\n\n\n- To Install themes for current user\n        \n        gnomelooks get [THEME-URL]\n\n- To Install themes globally\n\n        sudo gnomelooks get [THEME-URL]\n\n### Installation\n\n    pip3 install -U gnomelooks\n\n## gnomelooks help Page\n\n    ~$ gnomelooks --help\n        Usage: gnomelooks [OPTIONS] COMMAND [ARGS]...\n\n        Theme Installer for Gnome, Xfce4, Kde \n\n        Options:\n        --install-completion  Install completion for the current shell.\n        --show-completion     Show completion for the current shell, to copy it or\n                                customize the installation.\n        --help                Show this message and exit.\n\n        Commands:\n        askenv  | ask deskenv\n        get     | Install new UI themes/icons\n        ls      | List installed themes and icons\n        rm      | Remove installed themes and icons\n        update  | Update installed themes and icons via this tool\n\n## update all themes and icons\n\nRun: `gnomelooks update --themes`\n',
    'author': 'Rishang',
    'author_email': 'rishangbhavsarcs@gmail.com',
    'maintainer': None,
    'maintainer_email': None,
    'url': None,
    'packages': packages,
    'package_data': package_data,
    'install_requires': install_requires,
    'entry_points': entry_points,
    'python_requires': '>=3.6,<4.0',
}


setup(**setup_kwargs)
