from _typeshed import Incomplete

console: Incomplete

def string_to_dict(string: str) -> dict[str, str]: ...
def safeget(dct: dict, *keys): ...
def to_datetime(string): ...
def print_warning(msg: str) -> None: ...
def print_error(msg: str) -> None: ...
