VERSION_YEAR = 2022
VERSION_MONTH = int('06')
VERSION_DAY = int('18')
VERSION_HOUR = int('06')
VERSION_MINUTE = int('20')
MAJOR_VERSION = 1
MINOR_VERSION = 5
PATCH_VERSION = 202206180620
version_date = '2022/06/18 06:20'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
