# Autogenerated by Astropy-affiliated package astropy_helpers's setup.py on 2021-09-16 18:31:58 UTC
from __future__ import unicode_literals
import datetime

version = "2.0.8"
githash = "231c409a632dcbf2beae1c2dea5b843d81ede511"


major = 2
minor = 0
bugfix = 8

release = True
timestamp = datetime.datetime(2021, 9, 16, 18, 31, 58)
debug = False

astropy_helpers_version = ""

try:
    from ._compiler import compiler
except ImportError:
    compiler = "unknown"

try:
    from .cython_version import cython_version
except ImportError:
    cython_version = "unknown"
