
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-14T09:49:54-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "076105e9613ef78745d37df3d9bf8a38ce1e28bd",
 "version": "0.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
