
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-15T09:39:21-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "39052636313c08400606c781ee55d1855ca99f33",
 "version": "3.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
