
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-20T11:06:27-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "0b8758b5434a95ad921e22e6431ada05a5f1a2e1",
 "version": "v0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
