COMPONENT_PROPS = {
    "onPress",
    "accessibilityLabel",
    "accessibilityActions",
    "onAccessibilityAction",
    "disabled",
    "nextFocusDown",
    "nextFocusForward",
    "nextFocusLeft",
    "nextFocusRight",
    "nextFocusUp",
    "testID",
    "accessible",
    "onLayout",
    "style",
}
