class CmdOption:
    def register(self, *args, **kv): ...

    def show(self): ...

    def get(self, key: str) -> dict: ...


class TerminalArgv:
    def get_command_args(self, cmd) -> dict | None: ...

    def __iter__(self): ...

    def __next__(self) -> (str, dict): ...

    def __len__(self): ...


class Context:
    def get(self, k): ...

    def set(self, k, v): ...
