info = {"message": "Update version", "commit": "f71002d086262597dbb2a373d569cd13df750834", "date": "2022-06-15 14:24:13 +0300", "branch": "release/1.5.0", "version": "1.4.1+235.gf71002d0"}

# This file is automatically generated by version.py
# Do not include it to git!
