
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-14T17:18:50-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "b3e50081fada2dc2241f1ab7614e26a0d93898e3",
 "version": "0.4.23"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
