
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-14T12:04:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ad2b6447143355b1e148604164999ca46be7ceb5",
 "version": "0.7.1.post.dev616"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
