from typing import Any, List, Mapping


class Row:
    pass


class SearchIterator:
    pass


class Table:
    def restrict_columns(self, col_spec) -> "Table": ...
    def client_readable(self, *args, **kws) -> "Table": ...
    def client_writable(self, *args, **kws) -> "Table": ...
    def client_writable_cascade(self, *args, **kws) -> "Table": ...
    def delete_all_rows(self): ...
    def add_rows(self, rows) -> List[Row]: ...
    def add_row(data: Mapping[str, Any]) -> Row: ...
    def get(self, *args, **kws) -> Row: ...
    def get_by_id(self, row_id, fetch=None) -> Row: ...
    def has_row(self, row) -> bool: ...
    def list_columns(self) -> List: ...
    def search(self, *args, **kws) -> SearchIterator: ...
    def to_csv(self) -> str: ...
