
# This file was generated by 'versioneer.py' (0.15) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json
import sys

version_json = '''
{
 "dirty": false,
 "error": null,
 "full-revisionid": "a5fef976c722b0b7ec50f91f7d3d444583f8856f",
 "version": "1.0.17"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
