info = {"message": "feat: DEV-2636: Dynamic Labels templates (#2527)", "commit": "9a415d130e26fec0d716da0db9fe7362894bcea1", "date": "2022-06-16 08:27:02 +0100", "branch": "release/1.5.0", "version": "1.4.1+237.g9a415d13.dirty"}

# This file is automatically generated by version.py
# Do not include it to git!
