# coding=utf-8
# --------------------------------------------------------------------------
# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License. See License.txt in the project root for license information.
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is regenerated.
# --------------------------------------------------------------------------

from ._apps_operations import AppsOperations
from ._assets_operations import AssetsOperations
from ._azure_regions_operations import AzureRegionsOperations
from ._cdf_operations import CdfOperations
from ._cdf_clusters_operations import CdfClustersOperations
from ._countries_operations import CountriesOperations
from ._customers_operations import CustomersOperations
from ._databases_operations import DatabasesOperations
from ._customer_orders_operations import CustomerOrdersOperations
from ._workorders_operations import WorkordersOperations
from ._external_operations import ExternalOperations
from ._external_access_operations import ExternalAccessOperations
from ._electrical_operations import ElectricalOperations
from ._welding_operations import WeldingOperations
from ._links_operations import LinksOperations
from ._machine_alarms_operations import MachineAlarmsOperations
from ._machine_utilization_operations import MachineUtilizationOperations
from ._me_operations import MeOperations
from ._measurement_form_schemas_operations import MeasurementFormSchemasOperations
from ._measurement_forms_instances_operations import MeasurementFormsInstancesOperations
from ._measuring_tools_operations import MeasuringToolsOperations
from ._power_operations import PowerOperations
from ._suppliers_operations import SuppliersOperations
from ._sustainability_operations import SustainabilityOperations
from ._tenants_operations import TenantsOperations
from ._upload_operations import UploadOperations
from ._users_operations import UsersOperations

from ._patch import __all__ as _patch_all
from ._patch import *  # type: ignore # pylint: disable=unused-wildcard-import
from ._patch import patch_sdk as _patch_sdk
__all__ = [
    'AppsOperations',
    'AssetsOperations',
    'AzureRegionsOperations',
    'CdfOperations',
    'CdfClustersOperations',
    'CountriesOperations',
    'CustomersOperations',
    'DatabasesOperations',
    'CustomerOrdersOperations',
    'WorkordersOperations',
    'ExternalOperations',
    'ExternalAccessOperations',
    'ElectricalOperations',
    'WeldingOperations',
    'LinksOperations',
    'MachineAlarmsOperations',
    'MachineUtilizationOperations',
    'MeOperations',
    'MeasurementFormSchemasOperations',
    'MeasurementFormsInstancesOperations',
    'MeasuringToolsOperations',
    'PowerOperations',
    'SuppliersOperations',
    'SustainabilityOperations',
    'TenantsOperations',
    'UploadOperations',
    'UsersOperations',
]
__all__.extend([p for p in _patch_all if p not in __all__])
_patch_sdk()