# coding: utf-8
# Generated by setup.py for PyCBC on 2022-06-15 15:23:57 +0000.

version = '2.0.4'
date = '2022-06-15 11:59:43 +0000'
release = True
last_release = '2.0.4'

git_hash = 'eb1f4d556177cc68be4ddaf4cf6b5b06cb541f70'
git_branch = 'None'
git_tag = 'v2.0.4'
git_author = 'Alex Nitz <alex.nitz@gmail.com>'
git_committer = 'GitHub <noreply@github.com>'
git_status = 'CLEAN: All modifications committed'
git_builder = 'Unknown User <>'
git_build_date = '2022-06-15 15:23:57 +0000'
git_verbose_msg = """Version: 2.0.4
Branch: None
Tag: v2.0.4
Id: eb1f4d556177cc68be4ddaf4cf6b5b06cb541f70
Builder: Unknown User <>
Build date: 2022-06-15 15:23:57 +0000
Repository status is CLEAN: All modifications committed"""
from pycbc._version import *
