# coding: utf-8

"""
    Python client for GIG based clouds (pc4g)

    RESTful api client to a GIG based cloud.  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pc4g.configuration import Configuration


class ExternalNetworkModel(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'external_network_id': 'int',
        'network': 'str',
        'gateway': 'str',
        'dhcp': 'bool',
        'subnet_mask': 'str',
        'name': 'str',
        'public': 'bool'
    }

    attribute_map = {
        'external_network_id': 'external_network_id',
        'network': 'network',
        'gateway': 'gateway',
        'dhcp': 'dhcp',
        'subnet_mask': 'subnet_mask',
        'name': 'name',
        'public': 'public'
    }

    def __init__(self, external_network_id=None, network=None, gateway=None, dhcp=None, subnet_mask=None, name=None, public=None, _configuration=None):  # noqa: E501
        """ExternalNetworkModel - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._external_network_id = None
        self._network = None
        self._gateway = None
        self._dhcp = None
        self._subnet_mask = None
        self._name = None
        self._public = None
        self.discriminator = None

        if external_network_id is not None:
            self.external_network_id = external_network_id
        if network is not None:
            self.network = network
        if gateway is not None:
            self.gateway = gateway
        if dhcp is not None:
            self.dhcp = dhcp
        if subnet_mask is not None:
            self.subnet_mask = subnet_mask
        if name is not None:
            self.name = name
        if public is not None:
            self.public = public

    @property
    def external_network_id(self):
        """Gets the external_network_id of this ExternalNetworkModel.  # noqa: E501


        :return: The external_network_id of this ExternalNetworkModel.  # noqa: E501
        :rtype: int
        """
        return self._external_network_id

    @external_network_id.setter
    def external_network_id(self, external_network_id):
        """Sets the external_network_id of this ExternalNetworkModel.


        :param external_network_id: The external_network_id of this ExternalNetworkModel.  # noqa: E501
        :type: int
        """

        self._external_network_id = external_network_id

    @property
    def network(self):
        """Gets the network of this ExternalNetworkModel.  # noqa: E501


        :return: The network of this ExternalNetworkModel.  # noqa: E501
        :rtype: str
        """
        return self._network

    @network.setter
    def network(self, network):
        """Sets the network of this ExternalNetworkModel.


        :param network: The network of this ExternalNetworkModel.  # noqa: E501
        :type: str
        """

        self._network = network

    @property
    def gateway(self):
        """Gets the gateway of this ExternalNetworkModel.  # noqa: E501


        :return: The gateway of this ExternalNetworkModel.  # noqa: E501
        :rtype: str
        """
        return self._gateway

    @gateway.setter
    def gateway(self, gateway):
        """Sets the gateway of this ExternalNetworkModel.


        :param gateway: The gateway of this ExternalNetworkModel.  # noqa: E501
        :type: str
        """

        self._gateway = gateway

    @property
    def dhcp(self):
        """Gets the dhcp of this ExternalNetworkModel.  # noqa: E501


        :return: The dhcp of this ExternalNetworkModel.  # noqa: E501
        :rtype: bool
        """
        return self._dhcp

    @dhcp.setter
    def dhcp(self, dhcp):
        """Sets the dhcp of this ExternalNetworkModel.


        :param dhcp: The dhcp of this ExternalNetworkModel.  # noqa: E501
        :type: bool
        """

        self._dhcp = dhcp

    @property
    def subnet_mask(self):
        """Gets the subnet_mask of this ExternalNetworkModel.  # noqa: E501


        :return: The subnet_mask of this ExternalNetworkModel.  # noqa: E501
        :rtype: str
        """
        return self._subnet_mask

    @subnet_mask.setter
    def subnet_mask(self, subnet_mask):
        """Sets the subnet_mask of this ExternalNetworkModel.


        :param subnet_mask: The subnet_mask of this ExternalNetworkModel.  # noqa: E501
        :type: str
        """

        self._subnet_mask = subnet_mask

    @property
    def name(self):
        """Gets the name of this ExternalNetworkModel.  # noqa: E501


        :return: The name of this ExternalNetworkModel.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this ExternalNetworkModel.


        :param name: The name of this ExternalNetworkModel.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def public(self):
        """Gets the public of this ExternalNetworkModel.  # noqa: E501


        :return: The public of this ExternalNetworkModel.  # noqa: E501
        :rtype: bool
        """
        return self._public

    @public.setter
    def public(self, public):
        """Sets the public of this ExternalNetworkModel.


        :param public: The public of this ExternalNetworkModel.  # noqa: E501
        :type: bool
        """

        self._public = public

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(ExternalNetworkModel, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, ExternalNetworkModel):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, ExternalNetworkModel):
            return True

        return self.to_dict() != other.to_dict()
