# coding: utf-8

"""
    Python client for GIG based clouds (pc4g)

    RESTful api client to a GIG based cloud.  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pc4g.configuration import Configuration


class GetObjectspaceModelLimits(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'bucket_name': 'str',
        'limit': 'int'
    }

    attribute_map = {
        'bucket_name': 'bucket_name',
        'limit': 'limit'
    }

    def __init__(self, bucket_name=None, limit=None, _configuration=None):  # noqa: E501
        """GetObjectspaceModelLimits - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._bucket_name = None
        self._limit = None
        self.discriminator = None

        if bucket_name is not None:
            self.bucket_name = bucket_name
        if limit is not None:
            self.limit = limit

    @property
    def bucket_name(self):
        """Gets the bucket_name of this GetObjectspaceModelLimits.  # noqa: E501


        :return: The bucket_name of this GetObjectspaceModelLimits.  # noqa: E501
        :rtype: str
        """
        return self._bucket_name

    @bucket_name.setter
    def bucket_name(self, bucket_name):
        """Sets the bucket_name of this GetObjectspaceModelLimits.


        :param bucket_name: The bucket_name of this GetObjectspaceModelLimits.  # noqa: E501
        :type: str
        """

        self._bucket_name = bucket_name

    @property
    def limit(self):
        """Gets the limit of this GetObjectspaceModelLimits.  # noqa: E501


        :return: The limit of this GetObjectspaceModelLimits.  # noqa: E501
        :rtype: int
        """
        return self._limit

    @limit.setter
    def limit(self, limit):
        """Sets the limit of this GetObjectspaceModelLimits.


        :param limit: The limit of this GetObjectspaceModelLimits.  # noqa: E501
        :type: int
        """

        self._limit = limit

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(GetObjectspaceModelLimits, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, GetObjectspaceModelLimits):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, GetObjectspaceModelLimits):
            return True

        return self.to_dict() != other.to_dict()
