
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-16T12:09:31+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "79532274bd561b7119782a0cc1af6aab2ad6b69a",
 "version": "0.7.1.post.dev632"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
