# coding: utf-8

"""
    Python client for GIG based clouds (pc4g)

    RESTful api client to a GIG based cloud.  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pc4g.configuration import Configuration


class InvoicePaymentTerms(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'payment_terms': 'str'
    }

    attribute_map = {
        'payment_terms': 'payment_terms'
    }

    def __init__(self, payment_terms=None, _configuration=None):  # noqa: E501
        """InvoicePaymentTerms - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._payment_terms = None
        self.discriminator = None

        self.payment_terms = payment_terms

    @property
    def payment_terms(self):
        """Gets the payment_terms of this InvoicePaymentTerms.  # noqa: E501

        Invoice Payment terms  # noqa: E501

        :return: The payment_terms of this InvoicePaymentTerms.  # noqa: E501
        :rtype: str
        """
        return self._payment_terms

    @payment_terms.setter
    def payment_terms(self, payment_terms):
        """Sets the payment_terms of this InvoicePaymentTerms.

        Invoice Payment terms  # noqa: E501

        :param payment_terms: The payment_terms of this InvoicePaymentTerms.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and payment_terms is None:
            raise ValueError("Invalid value for `payment_terms`, must not be `None`")  # noqa: E501

        self._payment_terms = payment_terms

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(InvoicePaymentTerms, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, InvoicePaymentTerms):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, InvoicePaymentTerms):
            return True

        return self.to_dict() != other.to_dict()
