# coding: utf-8

"""
    Python client for GIG based clouds (pc4g)

    RESTful api client to a GIG based cloud.  # noqa: E501

    OpenAPI spec version: v1.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from pc4g.configuration import Configuration


class MenejaStructsVcoDataclassesVcoCustomerComplianceStruct(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'customer_id': 'str',
        'customer_name': 'str',
        'issues_count': 'int'
    }

    attribute_map = {
        'customer_id': 'customer_id',
        'customer_name': 'customer_name',
        'issues_count': 'issues_count'
    }

    def __init__(self, customer_id=None, customer_name=None, issues_count=None, _configuration=None):  # noqa: E501
        """MenejaStructsVcoDataclassesVcoCustomerComplianceStruct - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._customer_id = None
        self._customer_name = None
        self._issues_count = None
        self.discriminator = None

        self.customer_id = customer_id
        self.customer_name = customer_name
        self.issues_count = issues_count

    @property
    def customer_id(self):
        """Gets the customer_id of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.  # noqa: E501

        Customer ID  # noqa: E501

        :return: The customer_id of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.  # noqa: E501
        :rtype: str
        """
        return self._customer_id

    @customer_id.setter
    def customer_id(self, customer_id):
        """Sets the customer_id of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.

        Customer ID  # noqa: E501

        :param customer_id: The customer_id of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and customer_id is None:
            raise ValueError("Invalid value for `customer_id`, must not be `None`")  # noqa: E501

        self._customer_id = customer_id

    @property
    def customer_name(self):
        """Gets the customer_name of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.  # noqa: E501

        Customer name  # noqa: E501

        :return: The customer_name of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.  # noqa: E501
        :rtype: str
        """
        return self._customer_name

    @customer_name.setter
    def customer_name(self, customer_name):
        """Sets the customer_name of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.

        Customer name  # noqa: E501

        :param customer_name: The customer_name of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.  # noqa: E501
        :type: str
        """
        if self._configuration.client_side_validation and customer_name is None:
            raise ValueError("Invalid value for `customer_name`, must not be `None`")  # noqa: E501

        self._customer_name = customer_name

    @property
    def issues_count(self):
        """Gets the issues_count of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.  # noqa: E501

        Number of issues count  # noqa: E501

        :return: The issues_count of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.  # noqa: E501
        :rtype: int
        """
        return self._issues_count

    @issues_count.setter
    def issues_count(self, issues_count):
        """Sets the issues_count of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.

        Number of issues count  # noqa: E501

        :param issues_count: The issues_count of this MenejaStructsVcoDataclassesVcoCustomerComplianceStruct.  # noqa: E501
        :type: int
        """
        if self._configuration.client_side_validation and issues_count is None:
            raise ValueError("Invalid value for `issues_count`, must not be `None`")  # noqa: E501

        self._issues_count = issues_count

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(MenejaStructsVcoDataclassesVcoCustomerComplianceStruct, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, MenejaStructsVcoDataclassesVcoCustomerComplianceStruct):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, MenejaStructsVcoDataclassesVcoCustomerComplianceStruct):
            return True

        return self.to_dict() != other.to_dict()
