
# This file was generated by 'versioneer.py' (0.21) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-17T20:54:49-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "2b6e1b1e2e0da8636e636289e92266c42e3e6483",
 "version": "2.1.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
