
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-05-06T15:29:41+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "97fe5b319dc208ef604cfc9386f6168f38b461ba",
 "version": "0.0.25"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
