
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-16T12:25:46+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5f8ff78872c3640e69872c6dbb38e76410144210",
 "version": "0.7.1.post.dev634"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
