"""
Domestic species.
"""
species = [
    "Anas platyrhynchos",
    "Anas platyrhynchos domesticus",
    "Anser anser",
    "Anser cygnoides",
    "Bos bubalis",
    "Bos taurus",
    "Bubalus bubalis",
    "Cairina moschata domestica",
    "Canis familiaris",
    "Canis familiaris domesticus",
    "Canis lupus familiaris",
    "Capra hircus",
    "Equus asinus",
    "Equus caballus",
    "Equus ferus caballus",
    "Felis catus",
    "Gallus domesticus",
    "Gallus gallus domesticus",
    "Homo sapiens",
    "Meleagris gallopavo",
    "Numida meleagris",
    "Ovis aries",
    "Phasianus meleagris",
    "Sus domesticus",
    "Sus scrofa domesticus",
]
