
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-14T22:09:58+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "22616f1323b853ea9aa1275adcf9b4c256a0ab2c",
 "version": "0.2.5.post0.dev78"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
