
# This file was generated by 'versioneer.py' (0.20) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-16T13:56:58-0400",
 "dirty": false,
 "error": null,
 "full-revisionid": "4c123c5d998b692c0f3b9ba835dc55bc5cd45ab6",
 "version": "0.2.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
