
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-16T11:56:12+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "e7d73726a6af5cc649ff189c268a943fd59ebf4b",
 "version": "0.7.1.post.dev630"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
