
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-14T16:07:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "ec276cda998b272d3c2575530b38bdc160c0f74a",
 "version": "0.2.5.post0.dev62"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
