def create(values = None):
  record = {
    "sampleId": None,
    "inReport": None,
    "ampTier": None,
    "acmgTier": None,
    "alternativeTierSystems": None,
    "calledBy": None,
    "genomeBuild": None,
    "chrom": None,
    "pos": None,
    "ref": None,
    "alt": None,
    "filter": None,
    "id": None,
    "qual": None,
    "chromRaw": None,
    "posRaw": None,
    "idRaw": None,
    "refRaw": None,
    "altRaw": None,
    "qualRaw": None,
    "filterRaw": None,
    "infoRaw": None,
    "formatRaw": None,
    "sampleRaw": None,
    "genotype": None,
    "readDepth": None,
    "refAlleleDepth": None,
    "altAlleleDepth": None,
    "altAlleleFraction": None,
    "refAlleleDepthFwdStrand": None,
    "refAlleleDepthRevStrand": None,
    "altAlleleDepthFwdStrand": None,
    "altAlleleDepthRevStrand": None,
    "altAlleleFractionFwdStrand": None,
    "altAlleleFractionRevStrand": None,

    "gene": None,
    "transcript": None,
    "variantClassification": None,
    "variantType": None,
    "hgvsG": None,
    "hgvsC": None,
    "hgvsP": None,
    "hgvsPShort": None,
    "hotspot": None,
    "zygosity": None,

    "interpretation": None
  }
  if values!=None:
    record.update(values)
  return record
