
# This file was generated by 'versioneer.py' (0.19) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-16T13:04:01+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "fda19ce4d2cfb20f7e78ef946631b251508d45c9",
 "version": "0.0.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
