
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-16T11:09:45+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "2d353bb0bd382737b1770bb5c6b66550947f236a",
 "version": "0.7.1.post.dev622"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
