
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-17T10:52:16-0600",
 "dirty": true,
 "error": null,
 "full-revisionid": "2c1d7b3fe23be2d8a951fa7282af8bd2b92923a6",
 "version": "0.0.4"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
