"""
Column labels in the images file.
"""
project_id = "project_id"
deployment_id = "deployment_id"
url = "location"
class_ = "class"
order = "order"
family = "family"
genus = "genus"
species = "species"
name = "common_name"
date = "timestamp"
objects = "number_of_objects"
