print('------------------------------------------------------')
print("8:")
print('from itertools import *\ncount_word = 0\nfor i in product(ИГРА, repeat=5):\n   if i.count(A) == 2: \n      count_word += 1 \nprint(count_word)')
print('------------------------------------------------------')
print("8:")
print('letters = ЕЛМРУ\ns=[]\nfor a in letters:\n   for b in letters:\n      for c in letters:\n         for d in letters:\n            s.append(a+b+c+d)\nprint(s.index(ЛЕЕЕ)+1)')
print('------------------------------------------------------')
print('14:')
print('x = chislo\ncnt = 0\nwhile x > 0:\n   if x % 8 == 7:\n      cnt += 1\n   x = x //8\n print(cnt)')
print('------------------------------------------------------')
print('15 naimenshee:')
print('a = 1\nwhile True:\n   for x in range(0, 1000):\n      for y in range(0,1000):\n         if not(uravnenie):\n            break\n      else:\n         continue\n      break\n   else:\n      print(a)\n   a+=1')
print('------------------------------------------------------')
print('15 del:')
print('def f(x,a):\n   return x%a == 0\na=1\nwhile True:\n   for x in range(1, 1000000):\n      if not(uravnenie):\n         break\n   else:\n      print(a)\n   a+=1')
print('------------------------------------------------------')
print('17:')
print('count = 0\n m=0\nf = open(17.txt)\nl=[int(i) for i in f]\nfor i in range(len(l)-1):\n   if (l[i]%3==0)or(l[i+1]%3 == 0):\n      count+=1\n      m=max(m,l[i]+;[i+1])\nprint(count,m)')
print('------------------------------------------------------')
print("25 maska:")
print('import itertools\ncif=0123456789\nfor r_a in range(3):\n   for r_b in range(3):\n      for x in itertools.product(cif, repeat=r_a):\n         a = туткавычки.join(x)\n         for y in itertools.product(cif, repeat=r_b):\n            b=.join(y)\n            s = int(12 + a + 45 + b)\n            if s < 10**6 and s % 51 == 0:\n               print(s,s//51)')
print('------------------------------------------------------')
print('25:')
print('for x in range():\n   divs = set()\n   for d in range(1, round(x**0,5)+1:\n      if x % d == 0:\n         divs.add(d)\n         divs.add(x//d)\n         if len(divs) > 5:\n            break\n   if len(divs) == 5:\n      print(sorted(divs)[2:-1])')
print('------------------------------------------------------')
print('prostoe 4islo:')
print('def prost(n):\n   for d in range(2,n):\n      if n % d == 0:\n         return False\n   return True')
print('------------------------------------------------------')