
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-20T15:52:26+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "bb9a11817b77ea0d3ad4db449c47cf6d075240c6",
 "version": "0.3.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
