VERSION_YEAR = 2022
VERSION_MONTH = int('06')
VERSION_DAY = int('16')
VERSION_HOUR = int('10')
VERSION_MINUTE = int('46')
MAJOR_VERSION = 1
MINOR_VERSION = 4
PATCH_VERSION = 202206161046
version_date = '2022/06/16 10:46'
version = '{}.{}.{}'.format(MAJOR_VERSION, MINOR_VERSION, PATCH_VERSION)
__all__  = ['MAJOR_VERSION', 'MINOR_VERSION', 'PATCH_VERSION', 'version_date', 'version']
