
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2022-06-20T12:14:42+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "286375ae8c6238cb4f91bd6f96cf47f66f4bdb8a",
 "version": "3.0.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
