__name__ = "nature-remo-fork-only-for-hacs-nature-remo"
__version__ = "0.3.3"
__author__ = "Shinya Fujino"
__author_email__ = "shf0811@gmail.com"
__maintainer__ = "kkiyama117"
__license__ = "MIT"
__description__ = "Python client for Nature Remo API"
__url__ = "https://github.com/kkiyama117/nature-remo"
