INDEX_PREFIX_SIZE = 3
INDEX_POINTER_SIZE = 8  # 64-bit file pointer
INDEX_SEGMENT_SIZE = INDEX_POINTER_SIZE * 256 ** INDEX_PREFIX_SIZE

HASH_SIZE = 20
ENTRY_HASH_SIZE = HASH_SIZE - INDEX_PREFIX_SIZE
COUNT_SIZE = 4  # 32-bit int
ENTRY_SIZE = ENTRY_HASH_SIZE + COUNT_SIZE
