# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2022-03-09 11:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_api_base', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='gender',
            field=models.CharField(choices=[('-', '-'), ('male', 'Male'), ('female', 'Female')], default='-', max_length=10),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='reset_key',
            field=models.CharField(blank=True, default='', max_length=30, null=True),
        ),
    ]
